### ISSUE TITLE
Setting up a Proxy FirebaseMessagingService to allow multiple Push service crashes the app

### ISSUE THREAD

**Issue by bikranttripathi** [customerio/customerio-reactnative#111]
**SDK version:** 2.2.0

**Environment:** Production

**Are logs available?** 

```
2023-03-10 16:59:00.240 7096-7756/app.extra.android E/AndroidRuntime: FATAL EXCEPTION: Firebase-Messaging-Intent-Handle
    Process: app.extra.android, PID: 7096
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.ApplicationInfo android.content.Context.getApplicationInfo()' on a null object reference
        at android.content.ContextWrapper.getApplicationInfo(ContextWrapper.java:211)
        at io.customer.messagingpush.CustomerIOPushNotificationHandler.handleNotification(CustomerIOPushNotificationHandler.kt:124)
        at io.customer.messagingpush.CustomerIOPushNotificationHandler.handleMessage(CustomerIOPushNotificationHandler.kt:113)
        at io.customer.messagingpush.CustomerIOFirebaseMessagingService$Companion.handleMessageReceived(CustomerIOFirebaseMessagingService.kt:103)
        at io.customer.messagingpush.CustomerIOFirebaseMessagingService$Companion.handleMessageReceived$default(CustomerIOFirebaseMessagingService.kt:93)
        at io.customer.messagingpush.CustomerIOFirebaseMessagingService.onMessageReceived(CustomerIOFirebaseMessagingService.kt:112)
        at app.extra.android.ExtraPushNotificationListenerService.onMessageReceived(ExtraPushNotificationListenerService.java:35)
        at com.google.firebase.messaging.FirebaseMessagingService.dispatchMessage(FirebaseMessagingService.java:235)
        at com.google.firebase.messaging.FirebaseMessagingService.passMessageIntentToSdk(FirebaseMessagingService.java:185)
        at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent(FirebaseMessagingService.java:172)
        at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(FirebaseMessagingService.java:161)
        at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$com-google-firebase-messaging-EnhancedIntentService(EnhancedIntentService.java:78)
        at com.google.firebase.messaging.EnhancedIntentService$$ExternalSyntheticLambda1.run(Unknown Source:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@18.1.0:2)
        at java.lang.Thread.run(Thread.java:1012)
```

**Describe the bug**
When proxying `remoteMessage` through `CustomerIOFirebaseMessagingService`, it crashes the app because CustomerIO expects application context but in `onMessageReceived` method the SDK is passing `this` as the context but not using `getApplicationContext()` or allowing  us to pass in the context to `CustomerIOFirebaseMessagingService`. 

The crash is coming from `CustomerIOPushNotificationHandler` when trying to fetch `context.applicationInfo` and since the context is not an `applicationContext`, applicationInfo is null.

**To Reproduce**

Register this custom Notification Listener in AndroidManifest and send a test push notification through CustomerIO console, it will crash the app.

```
public class ExtraPushNotificationListenerService extends FirebaseMessagingService {

    private static final String TAG = "NotificationListener";

    private final RNPushNotificationListenerService mRNPushNotificationListenerService;
    private final CustomerIOFirebaseMessagingService mCustomerIOFirebaseMessagingService;

    public ExtraPushNotificationListenerService() {
        super();
        mRNPushNotificationListenerService = new RNPushNotificationListenerService();
        mCustomerIOFirebaseMessagingService = new CustomerIOFirebaseMessagingService();
    }

    @Override
    public void onMessageReceived(@NonNull RemoteMessage remoteMessage) {
        Map<String, String> data = remoteMessage.getData();
        String cioDeliveryToken = data.getOrDefault("CIO-Delivery-Token", null);
        Log.d(TAG,"onMessageReceived: cioDeliveryToken" + cioDeliveryToken);
        if (cioDeliveryToken != null) {
            Log.d(TAG,"CIO Push Notification Received. Let CustomerIO Handle it");
            mCustomerIOFirebaseMessagingService.onMessageReceived(remoteMessage);
        } else {
            Log.d(TAG,"Regular Push Notification Received");
            mRNPushNotificationListenerService.onMessageReceived(remoteMessage);
        }
    }

    @Override
    public void onNewToken(@NonNull String newToken) {
        Log.d(TAG, "New Notification Token");
        mRNPushNotificationListenerService.onNewToken(newToken);
        mCustomerIOFirebaseMessagingService.onNewToken(newToken);
    }
}
```

**Expected behavior**
I should be able to proxy Notification to either CustomerIO or any other Service provider based on the identifier present in the notification data without having the app crash

**Comment by mrehan27** [comment]
Hi @bikranttripathi. Thanks for sharing the details and code samples. I see you are creating object to use methods from `CustomerIOFirebaseMessagingService`. It is a service and this doesn't work very well for services as they have their own lifecycle. However, we do provide an option to allow our SDK work with custom services. To achieve the desired results, you can skip creating service instance and use these code snippets instead:

**Handle Message**

```
val handled = CustomerIOFirebaseMessagingService.onMessageReceived(context, message)
if (handled) {
    // Push notification has been handled
} else {
    // Push notification not handled, probably not Customer.io notification
}
```

**Register Token**

```
CustomerIOFirebaseMessagingService.onNewToken(context, token)
```

You can read more on implementing custom service in [our Android docs](https://www.customer.io/docs/sdk/android/push/#set-up-push).

Closing this as this should fix the issue you are facing, please feel free to ask more questions or re-open if this doesn't fix your issue.
