### ISSUE TITLE
Cannot find module '../package.json' from 'node_modules/customerio-reactnative/lib/commonjs/CustomerioTracking.js' when running tests

### ISSUE THREAD

**Issue by cauevsilva** [customerio/customerio-reactnative#41]
**SDK version:**  "customerio-reactnative": "^1.0.0",

**Environment:** Development

**Are logs available?** No SDK logs. The issue is happening when running jest tests

**Describe the bug**
We are implementing the SDK to allow push notifications on our React Native app with Expo. 

When running our tests (jest) we are seeing the following exception: 

` FAIL  __tests__/App_test.js
  ● Test suite failed to run

    Cannot find module '../package.json' from 'node_modules/customerio-reactnative/lib/commonjs/CustomerioTracking.js'

    Require stack:
      node_modules/customerio-reactnative/lib/commonjs/CustomerioTracking.js
      node_modules/customerio-reactnative/lib/commonjs/index.js
      App.js
      __tests__/App_test.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/customerio-reactnative/lib/commonjs/CustomerioTracking.tsx:4:13)
`

The offending code is at CustomerioTracking file line 20
`var pjson = require('../package.json');`

But looking at the node_modules structure, the package.json is located one level higher: 
`../../package.json`

When manually updating the CustomerioTracking to `var pjson = require('../..package.json')` the exception goes away. 

**To Reproduce**
`npm install customerio-reactnative`

Create an App_test.js
```
import React from 'react'
import 'react-native'
import { Provider } from 'react-redux'
import renderer from 'react-test-renderer'
// Note: test renderer must be required after react-native.
import App from '../App'
import store from '../src/redux/store'

jest.useFakeTimers()

it('renders correctly', () => {
  renderer.create(
    <Provider store={store}>
      <App />
    </Provider>
  )
})

```
Run jest test from CLI
(our script below, but the config file is not changing anything on path from modules)
`jest --verbose --config jest.config.js`

**Expected behavior**
No not found exception thrown on test runs.

**Comment by cauevsilva** [comment]
I just tested pulling latest version `"customerio-reactnative": "^1.0.1-alpha.1",` and the not found exception persists

**Comment by ami-aman** [comment]
Hi @cauevsilva 
Thanks for bringing this to our notice. I wanted to let you know that we are investigating it internally and will get back to you soon. Meanwhile if you have any other related queries, feel free to comment and let us know!

**Comment by superphil0** [comment]
can confirm this bug, also in 1.0.1-alpha.1

**Comment by ami-aman** [comment]
Hi @cauevsilva @superphil0 
Thank you for your patience. 

We have made this fix in our latest react native package release i.e. `1.0.1-alpha.1`. Please let me know if it works for you now.

**Comment by ami-aman** [comment]
Closing due to inactivity. Feel free to re-open if this doesn't fix the issue for you !
